config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'tags/show'
    get 'tags/create'
  end
  devise_for :admins,skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
    # ログインのURLを設定
  }
  devise_for :users,skip: [:passwords], controllers: {
    # userのパスワードは必要ないので、skipにしています。
    registrations: "user/registrations",
    # 新規登録のURLを設定
    sessions: "user/sessions"
    # ログインのURLを設定
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    # resourcesはindex,show,new,creste,edit,update,destroyを勝手に設定してくれます
    # only: にすると上記の７種類の中で好きなものだけ設定できます
    resources :posts, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    end
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'tag' => 'tags#tag_index', as: 'tag_index'
    resources :tag_posts, only: [:update]
  end



  scope module: :user do
    root to: "homes#top"
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    get 'about' => 'homes#about', as: 'about'
    resources :users
    resources :posts do
      resources :reviews
    end

    get 'mypage' => 'users#mypage', as: 'mypage'
    patch 'mypage' => 'users#update_mypage', as: 'update_mypage'
    get 'edit_mypage' => 'users#edit_mypage', as: 'edit_mypage'
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # ↑退会確認ページを表示するためのルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    # ↑論理削除するためのルーティング、patchにするのが大事
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'search'
        get 'autocomplete' # この１行を追記
      end
    end
    resources :tag_posts
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_posts, dependent: :destroy
  has_many :posts, through: :tag_posts, dependent: :destroy

  validates :tag_name, uniqueness: true, presence: true

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  def index
    @tag_lists = Tag.all
  end

  def tag_index
    @tags = Tag.where(post_id :post_id)
  end

  def create
    @post = Post.find(params[:post_id])
    redirect_to root_path
  end

  def edit
    @tag_lists = Tag.find(params[:id])
  end

  def update
    @tag_lists = Tag.find(params[:id])
    if @tag_lists.update(tag_params)
        redirect_to admin_tags_path
    else
        flash[:cannot_update_of_admin_tags] = "「タグ名」を入力してください。"
        redirect_to admin_tags_path
    end
  end

  def destroy
    @tag_lists = Tag.find(params[:id])
    @tag_lists.destroy
    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name, :post_id)
  end

end

app/controllers/user/tags_controller.rb
class User::TagsController < ApplicationController


  def index
    tag = Tag.find(params[:id])
    @posts = tag.posts
    #↑の記述はタグのidに紐づいた投稿の取得
    @tag = Tag.find(params[:id])
    #↑の記述はタグ名を表示するため
  end

  def create
    @post = Post.find(params[:tag][:post_id])
    @tag_list = params[:tag][:tag_name].split(",")
    if @post.save_tag(@tag_list)
       redirect_to post_path(@post.id)
    else
       flash[:cannot_save_of_tags] = "「タグ名」を入力してください。"
       redirect_to post_path(@post.id)
       #flash[:cannot_save_of_tags] = "「タグ名」を入力してください。"
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name, :post_id)
  end

end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/user/tags_helper.rb
module User::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="row justify-content-center">
  <div class="col col-auto">
  
    <h3 class="p-3 mb-2 bg-warning text-dark">タグ編集</h3>
    <%= form_with model: @tag_lists, url: admin_tag_path(@tag_lists.id) do |f| %>
      <%= f.text_field :tag_name %>
      <%= f.submit '変更を保存', class:'btn btn-primary'%>
    <% end %>

  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="row justify-content-center">
  <h3 class="p-3 mb-2 bg-warning text-dark">タグ一覧</h3>
</div>

<div class="row justify-content-center">
  <%= flash[:cannot_update_of_admin_tags] %>
</div>

<div class="row justify-content-center">
  <table class='table-dark table-bordered table-hover' width="90%" height="20">
    <thead>
      <tr>
        <th>タグid</th>
        <th>タグ名</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @tag_lists.each do |tag| %>
      <tr>
        <td><%= tag.id %></td>
        <td><%= tag.tag_name %></td>
        <td><%= link_to '編集', edit_admin_tag_path(tag.id), class:'btn btn-success' %>
            <%= link_to '削除', admin_tag_path(tag.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:'btn btn-danger' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>