config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'tags/show'
    get 'tags/create'
  end
  devise_for :admins,skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
    # ログインのURLを設定
  }
  devise_for :users,skip: [:passwords], controllers: {
    # userのパスワードは必要ないので、skipにしています。
    registrations: "user/registrations",
    # 新規登録のURLを設定
    sessions: "user/sessions"
    # ログインのURLを設定
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    # resourcesはindex,show,new,creste,edit,update,destroyを勝手に設定してくれます
    # only: にすると上記の７種類の中で好きなものだけ設定できます
    resources :posts, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    end
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'tag' => 'tags#tag_index', as: 'tag_index'
    resources :tag_posts, only: [:update]
  end



  scope module: :user do
    root to: "homes#top"
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    get 'about' => 'homes#about', as: 'about'
    resources :users
    resources :posts do
      resources :reviews
    end

    get 'mypage' => 'users#mypage', as: 'mypage'
    patch 'mypage' => 'users#update_mypage', as: 'update_mypage'
    get 'edit_mypage' => 'users#edit_mypage', as: 'edit_mypage'
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # ↑退会確認ページを表示するためのルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    # ↑論理削除するためのルーティング、patchにするのが大事
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'search'
        get 'autocomplete' # この１行を追記
      end
    end
    resources :tag_posts
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :user_image
         has_many :posts, dependent: :destroy
         has_many :reviews, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true
  

  # is_deletedがfalse(会員登録中、つまり退会していない)ならtrueを返す(ログインできる)ようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now # ← Confirmable を設定している場合は追加
      # user.name = "ゲストユーザー" # ←ユーザー名を設定している場合は追加
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
    # ページネーションのための記述.per(10)で１ページのうちで表示できるデータ数を10件にする
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :self_introduction, :is_deleted, :user_image)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @tag_lists = Tag.all
  end

  def about
  end
  
  def guest_sign_in
   user = User.find_or_create_by(email: 'guest@example.com') do |user|
     # find_or_create_byは()を見つけて、あるなしで条件を決める
     user.password = SecureRandom.urlsafe_base64
     # ランダムで64文字を組み合わせてパスワードを生成
     user.last_name = "ゲスト"
     user.first_name = "太郎"
     user.last_name_kana = "ゲスト"
     user.first_name_kana = "タロウ"
     user.user_name = "ゲストユーザー"
   end
   sign_in user
   redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
 
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  #全てのアクションの前にuserのログインしているかどうかを確認するdeviseのメソッド
  impressionist :actions => [:show], :unique => [:session_hash]

  def index
    @tag_list = Tag.all.page(params[:page]).per(10)
    #↑ビューでタグ一覧を表示するために全取得。
    if params[:tag_name].present?
      tag = Tag.find_by(tag_name: params[:tag_name])
      if tag.present?
       @posts = tag.posts.page(params[:page]).per(10)
      else
       @posts = Post.all.page(params[:page]).per(10)
      end
    else
     @posts = Post.all.page(params[:page]).per(10)
    end
    @post = current_user.posts.new
    #↑ビューのform_withのmodelに使う。
    @users = User.all
  end

  def new
    @post = Post.new
    #↑新規投稿のフォームを作成する
    @tag = Tag.new
    @tag_lists = Tag.all
    #↑DBにあるタグを全て取得
  end

  def create
    @post = current_user.posts.new(post_params)
    @tag_list = params[:post][:tag_name].split(',')
    #↑post,tag_nameのparamsから取ったデータを「,」で分けて@tag_listに入れる
    if @post.save
      @post.save_tag(@tag_list)
      #上の@tag_listで入れたデータをsave_tag(post.rbに記述)に入れる
      redirect_to posts_path
    else
      #render :new
      redirect_to new_post_path
      # 空欄で投稿画面に戻る
      flash[:cannot_save_of_posts] = "「店の名前」もしくは「店の説明」を入力してください。"
    end
  end

  def show
    @post = Post.find(params[:id])
    #↑クリックした投稿のidを取得
    @post_tags = @post.tags.distinct
    #↑@postに紐づいたtagを取得し、distinctで重複したものをまとめる
    @user = User.find(@post.user_id)
    #↑投稿のuser_idを取得し、@userに入れる
    @reviews = @post.reviews
    #↑投稿のidに紐づいたreviewだけを呼び出して並べたい
    @tag_show = Tag.new
    #↑postのshowページで新しくタグを作るためにnewでフォームを作成
  end

  def edit
    @post = Post.find(params[:id])
    #↑クリックした投稿のidを取得
  end

  def update
    @post = Post.find(params[:id])
    #↑クリックした投稿のidを取得
    if @post.update(post_params)
    #↑(post_params)に入っていて、@postで取得したデータをupdateでする
        redirect_to post_path(@post.id)
    else
        flash[:cannot_update_of_posts] = "「店の名前」もしくは「店の説明」を入力してください。"
        render :edit
    end
  end

  private
  #↓viewで投稿したときに下でpermit(許可)したデータをpost_paramsに入れる
  def post_params
    params.require(:post).permit(:user_id, :shop_name, :shop_explanation, :address, :latitude, :longitude, :is_released, :post_image)
  end

  #↓viewで投稿したときに下でpermit(許可)したデータをtag_paramsに入れる
  def tag_params
    params.require(:tag).permit(:tag_name)
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :user_name])
   end
   #ユーザーが新規登録createを行う際に、これらのパラメータをコントローラーで受け取ることができる

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  
  def new
    @post = Post.find(params[:post_id])
    # どの投稿にコメントするの？=>reviewのshowでidを渡した、new_review_path(post_id: @post.id)のidにコメントするで
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    #newから受け取ったレビューの各種内容を持ってくるnew⇨review_params⇨createと飛ばして行っている
    @review.user_id = current_user.id
    # @review.user_idで@reviewのuser_idに、current_user.idを入れる。これで@reviewに必要な情報を渡すことができる
    if @review.save
      redirect_to posts_path
    else
      redirect_to posts_path
      flash[:cannot_save_of_reviews] = "レビューの星を入力してください。レビューの保存はされませんでした。"
    end
    # reviewを、誰が（カレントユーザーが）、どの投稿（もとのpostのshowのidは？）に書くのかということを記述できていなかった
  end

  def index
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to post_review_path(post_id: @review.id)
  end

  private

  def review_params
    params.require(:review).permit(:post_id, :user_id, :review_title, :shop_review, :rate, :is_released)
  end

  def post_params
    params.require(:post).permit(:user_id, :shop_name, :shop_explanation, :address, :latitude, :longitude, :is_released, :post_image)
  end

  def user_params
    params.require(:user).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :self_introduction, :is_deleted, :user_image)
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def guest_sign_in
    user = User.guest # ← user.rbで定義したメソッド
    sign_in user
    redirect_to root_path
  end
  
end

app/controllers/user/tags_controller.rb
class User::TagsController < ApplicationController


  def index
    tag = Tag.find(params[:id])
    @posts = tag.posts
    #↑の記述はタグのidに紐づいた投稿の取得
    @tag = Tag.find(params[:id])
    #↑の記述はタグ名を表示するため
  end

  def create
    @post = Post.find(params[:tag][:post_id])
    @tag_list = params[:tag][:tag_name].split(",")
    if @post.save_tag(@tag_list)
       redirect_to post_path(@post.id)
    else
       flash[:cannot_save_of_tags] = "「タグ名」を入力してください。"
       redirect_to post_path(@post.id)
       #flash[:cannot_save_of_tags] = "「タグ名」を入力してください。"
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name, :post_id)
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def mypage
    @user = current_user
    #↑current_userの情報をとるときはこのくらいシンプルにとる。
    # 前までやっていたcurrent_user.idにしてしまうとidしか取ってこなくなるので、このくらいシンプルに書く
  end

  def edit_mypage
    @user = current_user
  end

  def update_mypage
    @user = current_user
    current_user.update(user_params)
    redirect_to mypage_path
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com'
      reset_session
      redirect_to :root
    else
      # 退会するユーザーのidを見つける
      @user.update(is_deleted: :true)
      # is_deletedをtrue(退会)にupdateする
      reset_session
      # セッション情報を全て削除します。
      flash[:notice] = "退会処理を実行しました"
      # viewにflashメッセージを表示するため
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :self_introduction, :is_deleted, :user_image)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/tags_helper.rb
module User::TagsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/edit.html.erb
<%= @user.user_name %><p>の情報編集</p>

<%= form_with model: @user, url: user_path(@user.id) do |f| %>

<p>ユーザー名</p>
<%= f.text_field :user_name %>

<p>自己紹介</p>
<%= f.text_area :self_introduction %>

<p>ユーザー画像</p>
<%= f.file_field :user_image %>

<%= f.submit '変更を保存' %>

<% end %>

<%= link_to '退会画面へ', unsubscribe_path %>

<%#= link_to '退会', user_path(@user.id), method: :patch, date: { confirm: "本当に退会しますか？" } %>

<%#= link_to 'レビュー一覧へ' %>

app/views/user/users/edit_mypage.html.erb
<div class="row justify-content-center">
  <h3 class="p-3 mb-2 bg-warning text-dark"><%= current_user.user_name %>の情報編集</h3>
</div>


<div class="row justify-content-center">
  <%= form_with model: @user, url: update_mypage_path do |f| %>
  
  <p class="p-3 mb-2 bg-warning text-dark">ユーザー名</p>
  <%= f.text_field :user_name %>
  
  <p class="p-3 mb-2 bg-warning text-dark">自己紹介</p>
  <%= f.text_area :self_introduction %>
  
  <p class="p-3 mb-2 bg-warning text-dark">ユーザー画像</p>
  <%= f.file_field :user_image, accept: "image/*" %>
  
  <div class="row justify-content-center">
    <%= f.submit '保存', class:"btn btn-primary" %>
  </div>
  
  <% end %>
</div>

<div class="row justify-content-center">
  <%= link_to '退会画面へ', unsubscribe_path(current_user), class:"btn btn-danger" %>
</div>

app/views/user/users/mypage.html.erb
<div class="row justify-content-center">
  <h3 class="p-3 mb-2 bg-warning text-dark"><%= current_user.user_name %>のマイページ</h3>
</div>

<div class="row justify-content-center">
  <p class="p-3 mb-2 bg-warning text-dark">ユーザー画像</p>
</div>

<div class="row justify-content-center">
  <% if current_user.user_image.attached? %>
  <%# もし user.use_image がつけられていたら？ %>
  <%= image_tag current_user.user_image, size: "200x200" %>
  <%# image_tag => 画像を表示するメソッド、 user.user_image => userテーブルのuser_imageメソッドから画像を引っ張る、 size: "50×50" =>画像の大きさを決定 %>
  <% else %>
  <%# そうでなければ %>
  <%= image_tag 'men_image.png', size: "200x200" %>
  <%# app/assets/image下にあるmen_image.pngを表示 %>
  <% end %>
</div>

<div class="row justify-content-center">
  <p class="p-3 mb-2 bg-warning text-dark">自己紹介</p>
</div>

<div class="row justify-content-center">
  <div class="p-3 mb-2 bg-dark text-white">
    <%= current_user.self_introduction %>
  </div>
</div>

<% if @user.email == 'guest@example.com' %>
 <div class="row justify-content-center">
  <p class="p-3 mb-2 bg-warning text-dark">ゲストユーザーはユーザー情報の編集ができません。</p>
 </div>
<% else %>
 <div class="row justify-content-center">
  <%= link_to '編集', edit_mypage_path(current_user), class:"btn btn-success" %>
 </div>
<% end %>

app/views/user/users/show.html.erb
<div class="row justify-content-center">
  <h3 class="p-3 mb-2 bg-warning text-dark"><%= @user.user_name %>の情報詳細</h3>
</div>

<div class="row justify-content-center">
  <% if @user.user_image.attached? %>
    <%= image_tag @user.user_image, size: "200x200" %>
  <% else %>
    <%= image_tag 'men_image', size: "200x200" %>
  <% end %>
</div>

<div class="row justify-content-center">
  <p class="p-3 mb-2 bg-warning text-dark">ユーザー名</p><br />
  <div class="p-3 mb-2 bg-dark text-white">
    <%= @user.user_name %>
  </div>
</div>

<div class="row justify-content-center">
  <p class="p-3 mb-2 bg-warning text-dark">自己紹介</p><br />
  <div class="p-3 mb-2 bg-dark text-white">
    <%= @user.self_introduction %>
  </div>
</div>

<div class="row justify-content-center">
  <% if current_user == @user.id %>
  <%# ここ、ログイン中のユーザーだと編集ボタンが出るように、それ以外は編集ボタンが出ないようにした！ %> 
   <%= link_to '編集', edit_user_path(@user.id) %>
  <% else %>
  <% end %>
</div>

app/views/user/users/unsubscribe.html.erb
<div class="row justify-content-center">
  <h3 class="p-3 mb-2 bg-warning text-dark">退会確認画面</h3>
</div>

<div class="row justify-content-center">
 <p class="p-3 mb-2 bg-warning text-dark">退会すると、これまでの投稿とレビューを<br />
 見ることができなくなります。<br />
 再度新規登録が必要になりますが、<br />
 本当に退会しますか？</p>
</div>

<div class="row justify-content-center">
 <%= link_to '退会する', withdraw_path, method: :patch, date: { confirm: "本当に退会しますか？" }, class:"btn btn-danger" %>
 <%# # users_withdraw=>論理削除用のurl
  method: :patch=>論理削除なのでpatch
  date: { confirm: "本当に退会しますか？" } 退会ボタンを押したときに画面上部に確認メッセージを出すための記述 %>
 
 <%= link_to '退会しない', mypage_path(current_user), class:"btn btn-success" %>
</div>