config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'tags/show'
    get 'tags/create'
  end
  devise_for :admins,skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
    # ログインのURLを設定
  }
  devise_for :users,skip: [:passwords], controllers: {
    # userのパスワードは必要ないので、skipにしています。
    registrations: "user/registrations",
    # 新規登録のURLを設定
    sessions: "user/sessions"
    # ログインのURLを設定
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    # resourcesはindex,show,new,creste,edit,update,destroyを勝手に設定してくれます
    # only: にすると上記の７種類の中で好きなものだけ設定できます
    resources :posts, only: [:index, :show, :edit, :update] do
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    end
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'tag' => 'tags#tag_index', as: 'tag_index'
    resources :tag_posts, only: [:update]
  end



  scope module: :user do
    root to: "homes#top"
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    get 'about' => 'homes#about', as: 'about'
    resources :users
    resources :posts do
      resources :reviews
    end

    get 'mypage' => 'users#mypage', as: 'mypage'
    patch 'mypage' => 'users#update_mypage', as: 'update_mypage'
    get 'edit_mypage' => 'users#edit_mypage', as: 'edit_mypage'
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # ↑退会確認ページを表示するためのルーティング
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    # ↑論理削除するためのルーティング、patchにするのが大事
    resources :tags, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'search'
        get 'autocomplete' # この１行を追記
      end
    end
    resources :tag_posts
  end

end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :post_image
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts, dependent: :destroy
  has_many :reviews, dependent: :destroy

  belongs_to :user

  validates :shop_name, presence: true
  validates :shop_explanation, presence: true

  geocoded_by :address
  after_validation :geocode

  #↓投稿のタグの作成のメソッド(user/posts_controller.rbのcreateアクションで使用)
  def save_tag(tag_list)
    #self.tags.pluck(:tag_name) unless self.tags.nil?
    if self.tags.pluck(:tag_name) == tag_list
      tag_posts_records = TagPost.where(post_id: self.id)
      tag_posts_records.destroy_all
    end
    #↑もしsaveしタグの名前が存在したら、前に入っていたかぶっているタグを消す

    tag_list = tag_list - self.tags.pluck(:tag_name)
    #↑tag_list -= self.tags.pluck(:tag_name)で同じ記述
    #↑tag_listに入っているものから元々入っていたものを引いて次のところに渡す記述

    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      self.tags << inspected_tag
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :user_image
         has_many :posts, dependent: :destroy
         has_many :reviews, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true
  

  # is_deletedがfalse(会員登録中、つまり退会していない)ならtrueを返す(ログインできる)ようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now # ← Confirmable を設定している場合は追加
      # user.name = "ゲストユーザー" # ←ユーザー名を設定している場合は追加
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  
  def index
    @posts = Post.all.page(params[:page]).per(10)
    # 投稿されたpostデータを一覧で表示する１ページに10件まで
  end

  def update
    @post = Post.find(params[:id])
    # views/admin/posts/show.html.erbの<%= form_with model: @post, url: admin_post_path do |f| %>で@postに入れられたデータ(どのidか)を見つける
    @post.update(post_params)
    # post_paramsに入れられた@postデータを更新
    redirect_to admin_post_path(@post.id)
    # @post.idに遷移
  end

  def show
    @post = Post.find(params[:id])
    # @postに入れられているidを見つける→showは表示だけ
    @reviews = @post.reviews
    #↑@postに紐づいたreviewを取得して@reviewsに格納
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :shop_name, :shop_explanation, :address, :latitude, :longitude, :is_released, :post_image)
    # postのハッシュの値だけ取得できるのでそれ以外の意味わからないものは取得しない。セキュリティのためのストロングパラメータ
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
    # ページネーションのための記述.per(10)で１ページのうちで表示できるデータ数を10件にする
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :self_introduction, :is_deleted, :user_image)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @tag_lists = Tag.all
  end

  def about
  end
  
  def guest_sign_in
   user = User.find_or_create_by(email: 'guest@example.com') do |user|
     # find_or_create_byは()を見つけて、あるなしで条件を決める
     user.password = SecureRandom.urlsafe_base64
     # ランダムで64文字を組み合わせてパスワードを生成
     user.last_name = "ゲスト"
     user.first_name = "太郎"
     user.last_name_kana = "ゲスト"
     user.first_name_kana = "タロウ"
     user.user_name = "ゲストユーザー"
   end
   sign_in user
   redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
 
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  #全てのアクションの前にuserのログインしているかどうかを確認するdeviseのメソッド
  impressionist :actions => [:show], :unique => [:session_hash]

  def index
    @tag_list = Tag.all.page(params[:page]).per(10)
    #↑ビューでタグ一覧を表示するために全取得。
    if params[:tag_name].present?
      tag = Tag.find_by(tag_name: params[:tag_name])
      if tag.present?
       @posts = tag.posts.page(params[:page]).per(10)
      else
       @posts = Post.all.page(params[:page]).per(10)
      end
    else
     @posts = Post.all.page(params[:page]).per(10)
    end
    @post = current_user.posts.new
    #↑ビューのform_withのmodelに使う。
    @users = User.all
  end

  def new
    @post = Post.new
    #↑新規投稿のフォームを作成する
    @tag = Tag.new
    @tag_lists = Tag.all
    #↑DBにあるタグを全て取得
  end

  def create
    @post = current_user.posts.new(post_params)
    @tag_list = params[:post][:tag_name].split(',')
    #↑post,tag_nameのparamsから取ったデータを「,」で分けて@tag_listに入れる
    if @post.save
      @post.save_tag(@tag_list)
      #上の@tag_listで入れたデータをsave_tag(post.rbに記述)に入れる
      redirect_to posts_path
    else
      #render :new
      redirect_to new_post_path
      # 空欄で投稿画面に戻る
      flash[:cannot_save_of_posts] = "「店の名前」もしくは「店の説明」を入力してください。"
    end
  end

  def show
    @post = Post.find(params[:id])
    #↑クリックした投稿のidを取得
    @post_tags = @post.tags.distinct
    #↑@postに紐づいたtagを取得し、distinctで重複したものをまとめる
    @user = User.find(@post.user_id)
    #↑投稿のuser_idを取得し、@userに入れる
    @reviews = @post.reviews
    #↑投稿のidに紐づいたreviewだけを呼び出して並べたい
    @tag_show = Tag.new
    #↑postのshowページで新しくタグを作るためにnewでフォームを作成
  end

  def edit
    @post = Post.find(params[:id])
    #↑クリックした投稿のidを取得
  end

  def update
    @post = Post.find(params[:id])
    #↑クリックした投稿のidを取得
    if @post.update(post_params)
    #↑(post_params)に入っていて、@postで取得したデータをupdateでする
        redirect_to post_path(@post.id)
    else
        flash[:cannot_update_of_posts] = "「店の名前」もしくは「店の説明」を入力してください。"
        render :edit
    end
  end

  private
  #↓viewで投稿したときに下でpermit(許可)したデータをpost_paramsに入れる
  def post_params
    params.require(:post).permit(:user_id, :shop_name, :shop_explanation, :address, :latitude, :longitude, :is_released, :post_image)
  end

  #↓viewで投稿したときに下でpermit(許可)したデータをtag_paramsに入れる
  def tag_params
    params.require(:tag).permit(:tag_name)
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :user_name])
   end
   #ユーザーが新規登録createを行う際に、これらのパラメータをコントローラーで受け取ることができる

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  
  def new
    @post = Post.find(params[:post_id])
    # どの投稿にコメントするの？=>reviewのshowでidを渡した、new_review_path(post_id: @post.id)のidにコメントするで
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    #newから受け取ったレビューの各種内容を持ってくるnew⇨review_params⇨createと飛ばして行っている
    @review.user_id = current_user.id
    # @review.user_idで@reviewのuser_idに、current_user.idを入れる。これで@reviewに必要な情報を渡すことができる
    if @review.save
      redirect_to posts_path
    else
      redirect_to posts_path
      flash[:cannot_save_of_reviews] = "レビューの星を入力してください。レビューの保存はされませんでした。"
    end
    # reviewを、誰が（カレントユーザーが）、どの投稿（もとのpostのshowのidは？）に書くのかということを記述できていなかった
  end

  def index
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to post_review_path(post_id: @review.id)
  end

  private

  def review_params
    params.require(:review).permit(:post_id, :user_id, :review_title, :shop_review, :rate, :is_released)
  end

  def post_params
    params.require(:post).permit(:user_id, :shop_name, :shop_explanation, :address, :latitude, :longitude, :is_released, :post_image)
  end

  def user_params
    params.require(:user).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :self_introduction, :is_deleted, :user_image)
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def guest_sign_in
    user = User.guest # ← user.rbで定義したメソッド
    sign_in user
    redirect_to root_path
  end
  
end

app/controllers/user/tags_controller.rb
class User::TagsController < ApplicationController


  def index
    tag = Tag.find(params[:id])
    @posts = tag.posts
    #↑の記述はタグのidに紐づいた投稿の取得
    @tag = Tag.find(params[:id])
    #↑の記述はタグ名を表示するため
  end

  def create
    @post = Post.find(params[:tag][:post_id])
    @tag_list = params[:tag][:tag_name].split(",")
    if @post.save_tag(@tag_list)
       redirect_to post_path(@post.id)
    else
       flash[:cannot_save_of_tags] = "「タグ名」を入力してください。"
       redirect_to post_path(@post.id)
       #flash[:cannot_save_of_tags] = "「タグ名」を入力してください。"
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name, :post_id)
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def mypage
    @user = current_user
    #↑current_userの情報をとるときはこのくらいシンプルにとる。
    # 前までやっていたcurrent_user.idにしてしまうとidしか取ってこなくなるので、このくらいシンプルに書く
  end

  def edit_mypage
    @user = current_user
  end

  def update_mypage
    @user = current_user
    current_user.update(user_params)
    redirect_to mypage_path
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com'
      reset_session
      redirect_to :root
    else
      # 退会するユーザーのidを見つける
      @user.update(is_deleted: :true)
      # is_deletedをtrue(退会)にupdateする
      reset_session
      # セッション情報を全て削除します。
      flash[:notice] = "退会処理を実行しました"
      # viewにflashメッセージを表示するため
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_name, :self_introduction, :is_deleted, :user_image)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/user/posts/edit.html.erb
<div class="row">
  <div class="col">
    <h3 class="p-3 mb-2 bg-warning text-dark"><%= @post.shop_name %>の編集</h3>
    
    <div class="row justify-content-center">
      <%= flash[:cannot_update_of_posts] %>
    </div>
    
    <%= form_with model: @post, url: post_path do |f| %>
    <%# @postのpost_path(rails routesで見て、VerbがPATCHでactionがupdate)を記述、編集するからPATCHのURLを選ぶ %>
    <%# |f|はブロック変数なので、下のフォームでブロック変数を設定することで、入力した情報を送信 %>
    
    <p class="p-3 mb-2 bg-warning text-dark">店の名前</p>
    
    <%= f.text_field :shop_name %>
    
    <p class="p-3 mb-2 bg-warning text-dark">店の説明</p>
    
    <%= f.text_area :shop_explanation %>
    
    <p class="p-3 mb-2 bg-warning text-dark">店の画像</p>
    
    <%= f.file_field :post_image, accept: "image/*" %>
    
    <p class="p-3 mb-2 bg-warning text-dark">右の地図で検索して入力してね！</p>
    
    <%= f.text_field :address %><br />
    
    <%= f.submit '保存', class:"btn btn-primary" %>
    <% end %>
  </div>
  
  <div class="col justify-content-center">
      <h3 class="p-3 mb-2 bg-warning text-dark">googlemap</h3>
  
       <!--地名入力用のinputを追加 -->
      <input id="address" type="textbox" value="東京">
      <%#↑value=""で最初に入っている地名を選べる%>
  
       <!--buttonをクリックしたらcodeAddressを実行　-->
      <input type="button" value="Encode" onclick="codeAddress()" class="btn btn-primary">
      <div id='map'>
      </div>
  
      <style>
      #map{
        height: 400px;
      }
      </style>
  
      <script>
      /*
      mapを関数の外で定義(codeAddressでも使うため)
      geocoderを用意
      */
  
      let map
      let geocoder
  
      function initMap(){
        // geocoderを初期化
        geocoder = new google.maps.Geocoder()
        <%# ↑新しいGeocoderを %>
  
        map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 36, lng: 140},
        <%#↑地図の初期位置をlat→緯度、lng→経度で設定できる%>
        zoom: 8
        });
      }
  
      function codeAddress(){
        // 入力を取得
        let inputAddress = document.getElementById('address').value;
  
        // geocodingしたあとmapを移動
        geocoder.geocode( { 'address': inputAddress}, function(results, status) {
          if (status == 'OK') {
      　　　　　　　　　　　　// map.setCenterで地図が移動
            map.setCenter(results[0].geometry.location);
  
      　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }
      </script>
      <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_API_KEY']%>&callback=initMap" async defer></script>
    </div>
    
  </div>

app/views/user/posts/show.html.erb
<div class="row">
  <div class="col">

    <h3 class="p-3 mb-2 bg-warning text-dark"><%= @user.user_name %>の投稿情報詳細</h3>

    <% if @post.post_image.attached? %>
      <%= image_tag @post.post_image, size: "100x100" %>
    <% else %>
      <%= image_tag 'men_image', size: "100x100" %>
    <% end %>

    <p class="p-3 mb-2 bg-warning text-dark text_align-center">店名</p>
    <div class="p-3 mb-2 bg-dark text-white">
      <%= @post.shop_name %>
    </div>

    <p class="p-3 mb-2 bg-warning text-dark">店の説明</p>
    <div class="p-3 mb-2 bg-dark text-white">
      <%= @post.shop_explanation %>
    </div>

    <% if @user.id == current_user.id %>
    <%# @user.idがcurrent_user.idだったらリンクを表示、違ったら表示なし %>
     <%= link_to edit_post_path(@post.id) do %>
     <button type="button" class="btn btn-success">編集</button><% end %>
    <% else %>
    <% end %>

    <p class="p-3 mb-2 bg-warning text-dark">店の地図</p>
    <script type="text/javascript">
         function initMap() {
           var test = {lat: <%= @post.latitude %>, lng: <%= @post.longitude %>};
           var map = new google.maps.Map(document.getElementById('map'), {
                     zoom: 15,
                     center: test
                     });
           var transitLayer = new google.maps.TransitLayer();
           transitLayer.setMap(map);
           var contentString = '住所：<%= @post.address %>';
           var infowindow = new google.maps.InfoWindow({
             content: contentString
           });
           var marker = new google.maps.Marker({
                         position:test,
                         map: map,
                         title: contentString
                       });
           marker.addListener('click', function() {
             infowindow.open(map, marker);
           });
         }
    </script>
       <script async defer
                 src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['MAP_API_KEY'] %>&callback=initMap">
                // ENV[...]は環境変数
       </script>
       <style type="text/css">
         #map { height: 200px;
               width: 70%;}
       </style>
       <div id="map"></div>
  </div>

  <div class="col">

    <div class="row justify-content-center">
      <%= flash[:cannot_save_of_tags] %>
    </div>

    <h3 class="p-3 mb-2 bg-warning text-dark">タグリスト</h3>
    <% @post_tags.each do |tag| %>
      <div class="p-3 mb-2 bg-dark text-white">
        <%= link_to tag.tag_name, tags_path(id: tag.id), class:"btn-outline-warning" %>
        <!--↑tags_path(id: tag.id)に遷移する-->
        <%= "(#{tag.posts.where(shop_name: @post.shop_name).count})" %>
        <%# タグが何件登録されたかの機能 %>
      </div>
    <% end %>

    <%= form_with model: @tag_show, url: tags_path do |f| %>
      <p class="p-3 mb-2 bg-warning text-dark">タグ名</p>
      <%= f.text_field :tag_name %>
      <%= f.hidden_field :post_id, :value => @post.id %>
      <%#↑のhidden_fieldでどの投稿にtagをつけるか、というデータを送る、そのために@post.idを送っている%>
      <%= f.submit '新規投稿', class:'btn btn-primary' %>
    <% end %>
    <p class="p-3 mb-2 bg-warning text-dark">↑空欄で新規投稿を押すとこのページを再表示します</p>



    <h3 class="p-3 mb-2 bg-warning text-dark"><%= @post.shop_name %>のレビュー一覧</h3>

    <table class='table-dark table-bordered table-hover' width="70%" height="40">
      <thead>
        <tr>
          <th>レビューユーザー名</th>
          <th>レビュータイトル</th>
          <th>星の数</th>
        </tr>
      </thead>
      <% @reviews.each do |review| %>
      <tbody>
        <%if review.is_released == true %>
        <!--↑reviewのis_released(boolean型)がtrueであれば、という意味-->
        <tr>
          <td><%= review.user.user_name %></td>
          <td>
              <%= link_to review.review_title, post_review_path(post_id: review.id), class:'btn btn-warning' %></td><%# controllerにpostに紐付いたreviewをeach文で作る %>
          <td><%= review.rate %></td>
        </tr>
        <% else %>
        <tr>
        </tr>
        <% end %>
      </tbody>
      <% end %>
    </table>

    <% if current_user.email == ENV['GUEST_EMAIL'] %>
      <div class="row justify-content-center">
    　　<p class="p-3 mb-2 bg-warning text-dark">ゲストユーザーはレビューができません。</p>
  　　</div>
　　<% else %>
      <%= link_to new_post_review_path(post_id: @post.id) do %>
      <button type="button" class="btn btn-primary">レビュー投稿</button><% end %>
    <% end %>
  </div>

</div>